apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pws.fullname" . }}
  labels:
    {{- include "pws.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pws.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pws.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 10 }}
      {{- end }}

      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "pws.serviceAccountName" . }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- with .Values.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.networkWatcher.enabled }}
        - name: network-watcher
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.networkWatcher.image.repository }}:{{ .Values.networkWatcher.image.tag }}"
          imagePullPolicy: {{ .Values.networkWatcher.image.pullPolicy }}
          {{- with .Values.networkWatcher.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: KUBE_CONNECTION
              value: cluster
            - name: SERVER_PORT
              value: "{{ .Values.service.port }}"
            - name: MEMORY_PERCENT
              value: "{{ .Values.networkWatcher.threshold }}"
            - name: CHECKING_INTERVAL
              value: "{{ .Values.networkWatcher.interval }}"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            httpGet:
              path: /health
              port: 6001
              httpHeaders:
              - name: X-Kube-Healthcheck
                value: "Yes"
            initialDelaySeconds: 5
            periodSeconds: 1
            failureThreshold: 1
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: 6001
              httpHeaders:
              - name: X-Kube-Healthcheck
                value: "Yes"
            initialDelaySeconds: 5
            periodSeconds: 1
            failureThreshold: 1
            successThreshold: 1
          resources:
            {{- toYaml .Values.networkWatcher.resources | nindent 12 }}
        {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          {{- with .Values.app.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: pws
              containerPort: 6001
              protocol: TCP
          {{- with .Values.app.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- with .Values.app.extraEnv }}
              {{- toYaml . | nindent 14 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: 6001
              httpHeaders:
              - name: X-Kube-Healthcheck
                value: "Yes"
            initialDelaySeconds: 5
            periodSeconds: 1
            failureThreshold: 1
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 6001
              httpHeaders:
              - name: X-Kube-Healthcheck
                value: "Yes"
            initialDelaySeconds: 5
            periodSeconds: 1
            failureThreshold: 1
            successThreshold: 1
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
